@startuml
class Idea {
    +points: Point[]
    +keyPointId: Int
    +addPoint(point: Point)
    +removePoint(id: Int)
}

class Project {
    +title
    +ideas: Idea[]
    +addIdea(idea: Idea)
    +removeIdea(id: Int)
}

Project --* Idea

interface ColumnElem {
    id: Int
    creationDate: Date
    +modifiedDate: Date
    +isArchived: Boolean
}

ColumnElem ..|> Idea
ColumnElem ..|> Project

class MainColumn {
    elements: ColumnElem[]
    +sort: Sort
    +filter: Filter

    +addElement(elem: MainColumnElem)
    +removeElement(id: Int)
}

MainColumn -* ColumnElem
@enduml
